waripub_main:
    resource: "@WaripubMainBundle/Controller/"
    type:     annotation
    prefix:   /
logout:
    path: /deconnexion
#fos_user:
#    resource: "@FOSUserBundle/Resources/config/routing/all.xml"