<?php

namespace Waripub\MainBundle\Repository;

/**
 * CategoriePubRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriePubRepository extends \Doctrine\ORM\EntityRepository
{
}
