<?php

namespace Waripub\MainBundle\Repository;

/**
 * PartageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartageRepository extends \Doctrine\ORM\EntityRepository
{
}
