<?php

namespace Waripub\MainBundle\Repository;
use Doctrine\ORM\EntityRepository;
use Waripub\MainBundle\Entity\User;


/**
 * PartageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartageRepository extends EntityRepository
{
    /**
     * Liste des partages faites sur les publicités d'un prestataire
     */
    public function partagePubParPrestataire(User $prestataire){

        $em = $this->getEntityManager();
        $query = $em->createQuery('
                SELECT p FROM WaripubMainBundle:Partage p 
                JOIN p.publication q 
                JOIN q.publicite u 
                WHERE u.prestataire = :user
            ')
            ->setParameter('user', $prestataire) ;

        return $query->getResult();
    }
}
