<?php

namespace Waripub\MainBundle\Repository;
use Doctrine\ORM\EntityRepository;
use Waripub\MainBundle\Entity\User;

/**
 * PublicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicationRepository extends EntityRepository
{
    /**
     * Liste des publications des publicités d'un prestataire
     */
    public function publicationPubParPrestataire(User $prestataire){
        /*
        return $this->createQueryBuilder("p")
            ->leftJoin("p.publicite", "pub")
            ->where("pub.prestataire = :user ")
            ->setParameter("user",$prestataire);
        */
        $em = $this->getEntityManager();
        $query = $em->createQuery('
                SELECT p FROM WaripubMainBundle:Publication p JOIN WaripubMainBundle:Publicite u
                WHERE u.prestataire = :user
            ')
            ->setParameter('user', $prestataire) ;

        return $query->getResult();
    }
}
