<?php

namespace Waripub\MainBundle\Repository;

/**
 * SouscripteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SouscripteurRepository extends \Doctrine\ORM\EntityRepository
{
}
